spring:
  profiles:
    active: local
  mvc:
    pathmath:
      matching-strategy: ant-patch-matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/demo-api
    username: postgres
    password: jucaprevost21112004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
